[profile]
pfpurl = "https://media.licdn.com/dms/image/v2/D5603AQHt8xwJzuPRGQ/profile-displayphoto-shrink_400_400/B56ZQCcJF1H0Ag-/0/1735207720107?e=1749686400&v=beta&t=OLlkJL2cXCtzXq65pOZEMoHZMt2HjDexX1VSg6qQ5TY"